/**
 * SPIDER-MAN: WEB CHASE - Configuration & State Constants
 */
const CONFIG = {
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  TARGET_FPS: 60,

  // Game States (Task 1)
  STATES: {
    BOOT: 'BOOT',
    TITLE: 'TITLE',
    CHASE_INTRO: 'CHASE_INTRO',
    CHASE: 'CHASE',
    WEB_MALFUNCTION: 'WEB_MALFUNCTION',
    RECOVERY: 'RECOVERY',
    WEB_SHOOTER_INSPECTION: 'WEB_SHOOTER_INSPECTION',
    DIAGNOSTICS: 'DIAGNOSTICS',
    DEBUGGING: 'DEBUGGING',
    REPAIR: 'REPAIR',
    SYSTEM_TEST: 'SYSTEM_TEST',
    CHASE_RESUME: 'CHASE_RESUME',
    BIRD_CAUGHT: 'BIRD_CAUGHT',
    MISSION_COMPLETE: 'MISSION_COMPLETE'
  },

  // Color Palette
  COLORS: {
    SPIDER_RED: 0xd41c30,
    SPIDER_RED_HEX: '#d41c30',
    SPIDER_BLUE: 0x183b6b,
    SPIDER_BLUE_HEX: '#183b6b',
    SPIDER_BLACK: 0x090e18,
    WEB_WHITE: 0xf5f8ff,
    TECH_CYAN: 0x00f0ff,
    TECH_CYAN_HEX: '#00f0ff',
    WARN_RED: 0xff2a45,
    WARN_RED_HEX: '#ff2a45',
    WARN_AMBER: 0xffaa00,
    WARN_AMBER_HEX: '#ffaa00',
    SUCCESS_GREEN: 0x30d158,
    SUCCESS_GREEN_HEX: '#30d158',
    GOLD_BIRD: 0xffb914,
    GOLD_BIRD_HEX: '#ffb914'
  },

  // Parallax Depths & Layer Speeds
  PARALLAX: {
    SKY: 0.0,
    CLOUDS: 0.04,
    DISTANT_SKYLINE: 0.12,
    MID_TOWERS: 0.28,
    MAIN_BUILDINGS: 0.55,
    ROOFTOP_EQUIP: 0.75,
    FOREGROUND_GIRDERS: 1.18,
    SPEED_LINES: 1.0
  },

  // Player & Swing Physics
  PLAYER_SPEED: 420,
  WEB_RANGE: 760,
  SWING_GRAVITY: 1250,
  SWING_DAMPING: 0.994,
  SWING_PUSH_FORCE: 340,
  SWING_RELEASE_BOOST_X: 1.35,
  SWING_RELEASE_BOOST_Y: 1.15,
  SWING_MIN_LENGTH: 80,
  SWING_MAX_LENGTH: 580,
  FORGIVING_AUTO_RELEASE_ANGLE: 155,
  PHYSICS: {
    GRAVITY: 980,
    AIR_DRAG: 0.992,
    GROUND_FRICTION: 0.88,
    RUN_ACCEL: 850,
    MAX_RUN_SPEED: 420,
    SWING_GRAVITY: 1250,
    SWING_PULL: 4.8,
    SWING_DAMPING: 0.994,
    RELEASE_BOOST_X: 1.35,
    RELEASE_BOOST_Y: 1.15,
    MAX_SPEED: 950,
    MIN_SWING_RADIUS: 80,
    MAX_SWING_RADIUS: 580
  },

  // Bird Chase & AI Waypoints
  BIRD: {
    BASE_SPEED: 320,
    MAX_SPEED: 480,
    MIN_SPEED: 180,
    CATCH_DISTANCE: 140, // Proximity required for web capture
    CHASE_ASSIST_MIN: 160,
    CHASE_ASSIST_MAX: 440,
    MALFUNCTION_TRIGGER_X: 3800, // Distance when bird triggers the misfire moment
    FINAL_CATCH_X: 6200
  },

  // Camera Settings
  CAMERA_LERP_X: 0.08,
  CAMERA_LERP_Y: 0.06,
  CAMERA_LEAD_X: 180,
  CAMERA_BASE_ZOOM: 1.0,
  CAMERA_FAST_ZOOM: 0.85,
  CAMERA_REVEAL_ZOOM: 1.85,
  CAMERA: {
    BASE_ZOOM: 1.0,
    FAST_ZOOM: 0.88,
    CINEMATIC_REVEAL_ZOOM: 2.1,
    WIDE_PULLBACK_ZOOM: 1.25,
    LERP_X: 0.08,
    LERP_Y: 0.07,
    LEAD_X: 160
  },

  // Telemetry Specs
  TELEMETRY: {
    NOMINAL_PSI: 450,
    FAULT_PSI: 14,
    SOLENOID_NOMINAL_TRAVEL: 100,
    SOLENOID_FAULT_TRAVEL: 18,
    HARMONIC_TARGET_HZ: 450
  },

  // FX Limits
  PARTICLE_LIMIT: 250,
  WIND_PARTICLE_COUNT: 28,
  SPARK_BURST_COUNT: 40
};

if (typeof window !== 'undefined') {
  window.CONFIG = CONFIG;
}
